<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CubotRedManager.Application\CubotRedManager.Application.csproj" />
    <ProjectReference Include="..\CubotRedManager.Infrastructure\CubotRedManager.Infrastructure.csproj" />
    <ProjectReference Include="..\CubotRedManager.Shared\CubotRedManager.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
